"""Add timestamp column

Revision ID: 0a327cd3cbf3
Revises: 8ac1591c868f
Create Date: 2025-06-19 23:34:42.977404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a327cd3cbf3'
down_revision = '8ac1591c868f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('matric_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('matric_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
