"""Your migration message here

Revision ID: 310768f2ca27
Revises: 
Create Date: 2025-06-19 16:18:42.537806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310768f2ca27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('matric_no', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
