"""Add location columns to StudentRecord

Revision ID: 7d586dfce828
Revises: 729f864d82b6
Create Date: 2025-06-26 12:38:44.730885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d586dfce828'
down_revision = '729f864d82b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(length=200), nullable=True))

    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.drop_column('location_name')
        batch_op.drop_column('accuracy')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('location_name')
        batch_op.drop_column('accuracy')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
